name: eval

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:      
      - name: Clone Golf Repo
        uses: actions/checkout@v3
        with:
          repository: evm-golf/golf

      - name: Install Dependencies
        run: npm install --save-dev

      - name: Eval
        run: npx hardhat run scripts/eval.js
        env:
          ISSUE: ${{ github.event.issue.number }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
